# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 15:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActivityName',
            new_name='ActivityType',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='activity_name',
            new_name='activity_type',
        ),
    ]
