# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 04:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_ionicuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ionicuser',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='ionicuser',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
