# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20160716_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ionicuser',
            name='sex',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ionicuser',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
