# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20160721_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_full_profile',
            field=models.BooleanField(default=False),
        ),
    ]
